version: 2
jobs:
  test:
    environment:
      CGO_ENABLED: "0"
    docker:
      - image: golang:alpine
    working_directory: /src
    steps:
      - run:
          name: Install git
          command: apk add git
      - checkout
      - run:
          name: Run tests
          command: go test -v ./...

workflows:
  version: 2
  development:
    jobs:
      - test