version: 2.1
jobs:
  test:
    environment:
      CGO_ENABLED: "0"
      GOCACHE: "/tmp/go/cache"
    docker:
      - image: golang:alpine
    working_directory: /src
    steps:
      - run:
          name: Install git
          command: apk add git
      - checkout
      - run:
          name: Run tests
          command: go test -v ./...
      - save_cache:
          key: cache-{{ checksum "go.sum" }}
          paths:
              - /tmp/go/cache
workflows:
  version: 2
  development:
    jobs:
      - test